### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by klausbadelt** [paypal/Payouts-Ruby-SDK#6]
Does/will this replace the [PayPal-Ruby-SDK](https://github.com/paypal/PayPal-Ruby-SDK)? What are the plans here?

We spent significant resources integrating the above, and are concerned and surprised to see this repo pop up with no explanation.

**Comment by rajkumarpalani** [comment]
@klausbadelt 2.0 Release candidate has been announced earlier - https://github.com/paypal/PayPal-Ruby-SDK#20-release-candidate

We have announced Payouts SDK in early Feb - https://developer.paypal.com/docs/payouts/reference/setup-sdk/#

Does/will this replace the PayPal-Ruby-SDK? What are the plans here?


> Does/will this replace the [PayPal-Ruby-SDK](https://github.com/paypal/PayPal-Ruby-SDK)? What are the plans here?
> 
PayPal-Ruby-SDK hosted all the PayPal API's in a single packaged SDK. As announced in the release candidate there will separate SDK's for every API with Checkout and Payouts being released so far. This provides a much better and easier integration option over the previous SDK. For Payouts API development and support will continue only on [Payouts-Ruby-SDK](https://github.com/paypal/Payouts-Ruby-SDK/issues/6)
